### ISSUE TITLE
Playground: TypeError: undefined is not an object (evaluating 't.options.map') on Safari

### ISSUE THREAD

**Issue by PremExtensi** [wix-incubator/pro-gallery#1081]
If you open Advanced Layout Options on Safari you'll get TypeError: undefined is not an object (evaluating 't.options.map')

**Comment by causeymackenzieson** [comment]
It seems like there's an issue with the code related to 't.options.map' in the Playground, specifically when running on Safari. It might be worth checking the compatibility of that code with Safari or debugging the specific part causing this error. Let's work together on this [website](https://tracking-locate.com/non-stop-delivery-nsd-tracking/) to troubleshoot and find a solution!

**Comment by Tannerschweitzer** [comment]
The error message "TypeError: undefined is not an object (evaluating 't.options.map')" typically indicates that there's an issue with accessing the 'options' property of an undefined object, specifically in a 'map' operation. To resolve this, you'll need to track down where this code [website](https://lesco.net.pk/) is being executed and ensure that the 't' object is properly defined before attempting to access its 'options' property.

If you need further assistance, providing more context or code snippets could help in diagnosing and resolving the issue.

**Comment by coralalbert** [comment]
The error "TypeError: undefined is not an object (evaluating 't.options.map')" in Safari typically occurs when the code is trying to access the map method on an undefined variable. This could be due to a missing or incorrectly initialized array. To fix it, ensure that t.options is properly defined and is an array before calling .map() on it. You may also want to add a check or use optional chaining (?.) to handle cases where t.options might be undefined.
