### ISSUE TITLE
Can't use with astro

### ISSUE THREAD

**Issue by Caligulaa** [wix-incubator/pro-gallery#1152]
Having same issue as #973 
Any magic workarounds ?

Thank you.

**Comment by Caligulaa** [comment]
Workaround: setting a global variable in pages where the component is used seems to work:

   <script is:inline>
      const global = '';
    </script>

**Comment by sanganimedia1** [comment]
> Workaround: setting a global variable in pages where the component is used seems to work:
> 
> <script is:inline> const global = ''; </script>

Thanks it help me to fix my [project ](https://frequencycaps.com/product/calm-microdose/)

**Comment by PaisleyLeah** [comment]
Usually, it can overcome the workload in my [domain](https://alphaag.ru/).

**Comment by EmilyThompson23** [comment]
If you're encountering issues with using a particular tool or library with Astro, as noted in issue #1152, it may be due to compatibility problems or configuration errors. Astro is a modern static site generator, and certain tools or plugins might not fully integrate with it. Check the documentation for both Astro and the tool in question to ensure compatibility and correct usage. Look for any updates or community discussions about similar issues. If needed, reach out to the developers or community forums for support in resolving the compatibility problem.
