### ISSUE TITLE
EventName LOAD_MORE_CLICKED & GALLERY_CHANGE Question

### ISSUE THREAD

**Issue by raulbarriga** [wix-incubator/pro-gallery#263]
When using the generated code from the playground with a load more button, & implementing the ProGallery component with some image items passed in, the load more button just console.logs the events but doesn't render more images.

Does the developer have to implement this functionality on their own or is it already included in the npm package.

Thanks.

**Comment by ido-postelnik** [comment]
Hi Raul,
Yes, you need to implement this functionality by your self. 
With your own implementation, you can decide if to fetch the next items from a server, load them from a local state or use any other functionality you define.

Good luck!

**Comment by raulbarriga** [comment]
And if I need to implement the load more functionality for the gallery, would I need the another package from wix like the [pro-gallery-lib](https://www.npmjs.com/package/pro-gallery-lib)?

**Comment by yhattav** [comment]
Hey, You dont need anything other than your own implementation.
The gallery sends the NEED_MORE_ITEMS event whenever it reaches the end of the gallery. This only lets you know that the user reached the end of the gallery (with padding) so that you can run your item fetching implementation and set the new items array to the gallery.
