### ISSUE TITLE
Issue on getting repository

### ISSUE THREAD

**Issue by EnricoBeltramo** [wix-incubator/pro-gallery#386]
When I try to get the repository I have follow error:

git clone https://github.com/wix/pro-gallery.git
Cloning into 'pro-gallery'...
remote: Enumerating objects: 41415, done.
remote: Counting objects: 100% (5459/5459), done.
remote: Compressing objects: 100% (1889/1889), done.
Receiving objects: 100% (41415/41415), 199.52 MiB | 13.32 MiB/s, done.d 35956 eceiving objects: 100% (41415/41415), 195.55 MiB | 9.30 MiB/s

Resolving deltas: 100% (28810/28810), done.
error: unable to create file packages/gallery/tests/e2e/styleParams/__image_snapshots__/gallery-size-type-e-2-e-spec-js-gallery-size-type-e-2-e-when-gallery-size-type-set-to-pixels-the-width-of-each-item-or-group-should-be-approximately-the-value-given-to-gallery-size-px-1-snap.png: Filename too long
error: unable to create file packages/gallery/tests/e2e/styleParams/__image_snapshots__/gallery-size-type-e-2-e-spec-js-gallery-size-type-e-2-e-when-gallery-size-type-set-to-ratio-the-width-of-each-item-or-group-should-be-approximately-the-value-given-to-gallery-size-ratio-in-percentage-from-the-gallery-total-width-1-snap.png: Filename too long
error: unable to create file packages/gallery/tests/e2e/styleParams/__image_snapshots__/hovering-behaviour-e-2-e-spec-js-hovering-behaviour-e-2-e-should-make-hover-state-disapear-on-hover-reverse-hover-when-hovering-behaviour-is-disappears-1-snap.png: Filename too long
error: unable to create file packages/gallery/tests/e2e/styleParams/__image_snapshots__/image-info-type-e-2-e-spec-js-image-info-type-e-2-e-should-attach-texts-and-image-and-apply-styles-to-both-as-one-container-image-info-type-attached-background-1-snap.png: Filename too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by yhattav** [comment]
Hey,
Do you still experience this in the latest version (^5)?

**Comment by Brodericksteven** [comment]
It seems like you're encountering an error while trying to clone the repository. The error message indicates that the filenames you're trying to create are too long. This can be a limitation imposed by the file system you're using.

To resolve this issue, you can try the following steps [click here](	https://nolcard.ae/):
Instead of cloning directly into the default directory, specify a shorter path for the destination folder.
If possible, use a file system with longer filename support, such as NTFS on Windows or APFS on macOS.
Consider renaming or shortening the filenames of the problematic files in the repository to avoid exceeding the maximum length limit.
If the issue persists, you can inspect the current status of your Git repository using 'git status' and try restoring the repository to a previous state using 'git restore --source=HEAD :/'.

**Comment by mia45943** [comment]
The error you encountered while trying to clone the repository is related to filenames being too long for your operating system to handle. This is a common issue, especially on Windows systems, where there are limitations on the maximum filename length.

To resolve this problem, you can try the following solutions:

Use a Git client with long filename support: Some Git clients, like Git for Windows (GitBash), handle long filenames better than the default command prompt. Try using GitBash or other Git clients that support longer filenames.

Enable long path support in Git: If you are using Git for Windows, you can enable long path support by running the following command in the command prompt or GitBash before cloning the repository:

arduino
Copy code
git config --global core.longpaths true
Clone to a different location: Try cloning the repository to a different directory with a shorter path. For example, clone it to the root directory of your drive (e.g., C:\pro-gallery) to reduce the overall path length.

Clone using SSH: If you have set up SSH access for your GitHub account, try cloning the repository using the SSH URL instead of the HTTPS URL. The SSH URL typically has a shorter path.

Shorten the file paths: If none of the above solutions work, you might need to manually shorten the file paths in the repository. This could involve renaming files or moving them to a different location within the repository.

Remember to always back up your repository before attempting any changes to avoid data loss. If you're still having trouble after trying these solutions, consider reaching out to the repository owners or seeking help from the GitHub community or technical support.

**Comment by mia45943** [comment]
The error message you're encountering is due to a filename that exceeds the maximum length allowed on your file system. This issue commonly occurs on Windows systems, which have a maximum filename length limit of 260 characters.

To resolve this issue and successfully clone the repository, you can try the following approaches:

Use a Shorter Directory Path: One way to work around the filename length limit is to clone the repository to a location with a shorter directory path. For example, clone it to a higher-level directory with a shorter path name.

Enable Long Paths on Windows: If you're using a Windows system with Git, you can enable support for long file paths by configuring Git to use the Windows Long Paths option. To do this, open a command prompt with administrator privileges and run the following command:

shell

git config --system core.longpaths true
After enabling long paths, try cloning the repository again.

Use Git Bash or Another Terminal: Some Windows users have reported success by using Git Bash or another terminal application instead of the default Windows Command Prompt. These terminals may have better support for longer file paths.

Use a Git GUI Client: Consider using a Git GUI client like Sourcetree or GitHub Desktop. These tools often have built-in support for handling long filenames more gracefully.

Shorten the Filenames: If you have control over the repository, you can try to shorten the filenames in the repository, especially the ones causing the issue. This would require making changes to the repository and pushing those changes, which may not always be feasible.

Use a Different File System: If you frequently work with repositories that have long filenames, consider using a file system that supports longer filenames, such as NTFS or a Linux file system, rather than the default FAT32 file system.

Please note that if you're not the repository owner, you may need to contact the repository maintainers to address the issue of long filenames in the repository, as it can affect other users as well.

**Comment by IzaiahKaysen** [comment]
Are you using Git, SVN, [blacktiedetailing](https://blacktiedetailing.com/), Mercurial, or another version control system?

**Comment by EverettBennett** [comment]
I'm facing such [instaflow apk download](https://theinstapro.net/insta-flow-apk/) issue for couple of days and need someone assistance on it!

**Comment by zesismark43** [comment]
The [cost of living in Portugal](https://nifportugal.net/cost-of-living-in-portugal/) is generally lower than in many other Western European countries and the USA.

**Comment by Gittulal** [comment]
The [acteia mod apk](https://modobr.com/acteia.html) is best apk to play and easy to beat.

**Comment by EverettBennett** [comment]
This issue are also having with me and I'm looking solution of [onstream tv](https://onstreamtv.net/).

**Comment by Gittulal** [comment]
click here to learn more about the recipes on [recipevilla](https://recipevilla.com/).
