### ISSUE TITLE
repo.dev.wixpress.com is down

### ISSUE THREAD

**Issue by Fmstrat** [wix-incubator/pro-gallery#900]
`npm install` fails due to this. I'm not sure where else to report this. Thanks!

```
$ npm install
npm WARN deprecated lerna-packages@0.0.1: use 'getPackages' from @lerna/project
npm WARN deprecated read-package-tree@5.3.1: The functionality that this package provided is now in @npmcli/arborist
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/which-boxed-primitive/-/which-boxed-primitive-1.0.2.tgz failed, reason: getaddrinfo ENOTFOUND repo.dev.wixpress.com
```

**Comment by Fmstrat** [comment]
This seems a bit odd. Why is `which-boxed-primitive` using a non open-code hosted version from wixpress vs the standard library? https://www.npmjs.com/package/which-boxed-primitive

**Comment by yhattav** [comment]
@nirnaor @shmuelhizmi

**Comment by nirnaor** [comment]
@yhattav I'm on it

**Comment by nirnaor** [comment]
@Fmstrat can you retry now?

**Comment by chrishardings** [comment]
It seems like there is a network issue that is preventing your computer from connecting to the https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/ URL. The error message "ENOTFOUND" is indicating that the hostname "repo.dev.wixpress.com" cannot be resolved. This could be caused by a number of issues including a problem with your internet connection or a firewall blocking the connection.

You can try resolving this issue by doing the following:

Check your internet connection and make sure it is stable and working properly
Try disabling any firewalls or anti-virus programs that may be blocking the connection
Try using a different network or internet connection to see if that resolves the issue
If none of the above steps work, you can try contacting the system administrator of https://repo.dev.wixpress.com/artifactory/api/npm/npm-repos/ or the [minecraft](https://minecraftapk.club/) support team for assistance.
It's also worth noting that some of the packages that you are trying to install are deprecated, so it's possible that this issue is related to the outdated packages you are trying to install. You may want to try updating these packages to their latest versions if possible.

**Comment by mangagoms** [comment]
Great thanks for sharing[!](https://mangago.ms/)

**Comment by robert-micheal** [comment]
The issue you're encountering is an `ENOTFOUND` error during the npm install command. This error typically indicates a problem with resolving the network address or connecting to the required resources. To address this problem, you can try the following steps:

Verify your internet connection: Ensure that you have a stable and working internet connection.

Clear the npm cache: Run the following command to clear the npm cache, which can sometimes resolve network-related issues:

`npm cache clean --force`

Retry the installation: Run` npm install` again and check if the issue persists. It's possible that the error was transient and can be resolved by retrying.

Check your network configuration: Ensure that you don't have any proxy or firewall settings blocking the npm registry or the specific resource being accessed during the installation. Adjust your network configuration if necessary.

Use a different network or VPN: If you're on a restricted network, try switching to a different network or use a VPN to bypass any limitations or restrictions.

If none of these steps resolve the issue, you may want to reach out to the package maintainers or consult the npm support channels for further assistance, as it could be an issue specific to the package or your network [environment.](https://superiorautoinstitute.com/)

**Comment by shmuelhizmi** [comment]
@robert-micheal no need, just delete the lock file and reinstall, I'll make sure we will fix it from our side soon

**Comment by MaciDallas** [comment]
Facing same issue in wix. Furthermore, [instagram pro for ios](https://instaapkpro.net/instapro-for-ios/) is an app available on the App Store that claims to offer a number of features that are not available in the official Instagram app, such as the ability to download photos and videos, view private stories, and ghost follow other users.
